spring:
  datasource:
    continueOnError: true
org:
  quartz:
    scheduler:
      instanceName: tenant1Jobs
      instanceId: tenant1
    threadPool:
      threadCount: 5
job:
  startDelay: 5000
  repeatInterval: 3000
  description: Sample job
  key: count